export const formations = [
  {
    id: 1,
    title:
      "Créer un menu hamburger moderne avec seulement HTML et CSS (Tutoriel rapide)",
    description:
      "Dans cette vidéo, découvre comment coder un **menu hamburger interactif avec uniquement HTML et CSS**. Pas besoin de JavaScript, parfait pour débutants ou développeurs voulant améliorer leurs bases en CSS !",
    src: "youtube",
    type: "video",
    image:
      "https://media.licdn.com/dms/image/v2/D4D22AQH5PcXPk-rjFw/feedshare-shrink_2048_1536/B4DZSDFZGfHUAo-/0/1737366017465?e=1740614400&v=beta&t=jRuFE2kVlNiJ3Y768hXTg2x5wRlLNtiawPasGN3mqpU",
    link: "https://www.youtube.com/watch?v=hDw0QGGdZI4&t=122s",
    author: "Elvin code",
    date: "20 janvier 2023",
    isVerifyed: true,
    isFree: true,
    price: 40,
    currency: "$",
    duration: "45 min",
  },
  {
    id: 2,
    title: "Comprendre les fonctions exponentielles",
    description:
      "Apprends à maîtriser les bases des fonctions exponentielles, étape par étape.",
    src: "document",
    type: "pdf",
    image: "",
    link: "https://www.example.com/fonctions-exponentielles",
    author: "Mathématiques pour tous",
    date: "10 février 2023",
    isVerifyed: true,
    isFree: false,
    price: 10,
    currency: "$",
    duration: "2h",
  },
  {
    id: 3,
    title: "Introduction à JavaScript pour les débutants",
    description:
      "Un guide interactif pour apprendre les bases de JavaScript et commencer à coder.",
    src: "youtube",
    type: "video",
    image:
      "https://media.licdn.com/dms/image/v2/D5612AQEuxVQRR7Z0dQ/article-cover_image-shrink_720_1280/article-cover_image-shrink_720_1280/0/1737541685763?e=1743033600&v=beta&t=iUhqX2LhYxFT3tIzBLHSq9NcrmAIqjoRvi3Metj7pIo",
    link: "https://www.youtube.com/watch?v=v3Ho7QVaTXM",
    author: "Melvynx",
    date: "15 mars 2023",
    isVerifyed: true,
    isFree: true,
    price: 0,
    currency: "$",
    duration: "1h 30 min",
  },
  {
    id: 4,
    title: "Les bases de React.js",
    description:
      "Découvre les concepts fondamentaux de React pour créer des interfaces dynamiques.",
    src: "course",
    type: "video",
    image:
      "https://media.licdn.com/dms/image/v2/D5612AQGzwXGETyzU5A/article-cover_image-shrink_720_1280/article-cover_image-shrink_720_1280/0/1737416375749?e=1743033600&v=beta&t=uQ5VbY697BkT6e1pUkTs-DO_5GYoEIaqE1V09gmUWI8",
    link: "https://www.udemy.com/course/react-for-beginners/",
    author: "John Doe",
    date: "5 mai 2023",
    isVerifyed: true,
    isFree: false,
    price: 42000,
    currency: "Fc",
    duration: "3h",
  },
  {
    id: 5,
    title: "Apprendre Tailwind CSS",
    description:
      "Explore comment styliser vos applications modernes rapidement grâce à Tailwind CSS.",
    src: "blog",
    type: "article",
    image:
      "https://media.licdn.com/dms/image/v2/C4E07AQGIGQ-B_jnjoA/group-logo_image-shrink_92x92/group-logo_image-shrink_92x92/0/1630999155307?e=1738159200&v=beta&t=kuLixvw8FQKqai73AtCthiOFfqi90MnTVS26dPq-FUw",
    link: "https://tailwindcss.com/docs/installation",
    author: "Tailwind Team",
    date: "12 avril 2023",
    isVerifyed: true,
    isFree: true,
    price: 0,
    currency: "$",
    duration: "30 min",
  },
  {
    id: 6,
    title: "Guide pratique de MongoDB",
    description:
      "Apprends à utiliser MongoDB pour stocker et interroger des données efficacement.",
    src: "ebook",
    type: "pdf",
    image:
      "https://media.licdn.com/dms/image/v2/D4D10AQFLefywaTwwzg/image-shrink_1280/image-shrink_1280/0/1736946001529?e=1738159200&v=beta&t=i1RCy1Anv9PL9i9hW0NbBgONmEOZgo2uYIDTRxFXrBU",
    link: "https://learn.mongodb.com/",
    author: "MongoDB University",
    date: "30 juin 2023",
    isVerifyed: true,
    isFree: true,
    price: 0,
    currency: "$",
    duration: "4h",
  },
  {
    id: 7,
    title: "Créer des animations CSS avancées",
    description:
      "Un cours approfondi pour maîtriser les animations CSS, de simples transitions aux animations complexes.",
    src: "youtube",
    type: "video",
    image:
      "https://media.licdn.com/dms/image/v2/D4E22AQGLb2KN7hdYXA/feedshare-shrink_2048_1536/B4EZSOMSVVHAAo-/0/1737552374654?e=1740614400&v=beta&t=QC3p0ySF1rbEwuIT5yK10jWTuVDBOfjpPCoMgRcOfJk",
    link: "https://www.youtube.com/watch?v=avw21xGxflU",
    author: "Bob Frontend",
    date: "7 juillet 2023",
    isVerifyed: true,
    isFree: true,
    price: 0,
    currency: "$",
    duration: "2h 15 min",
  },
  {
    id: 8,
    title: "Atelier de développement Node.js",
    description:
      "Un atelier pratique pour apprendre à créer des API backend avec Node.js.",
    src: "course",
    type: "workshop",
    image:
      "https://media.licdn.com/dms/image/v2/C510BAQG_1VWEGBmO9A/company-logo_200_200/company-logo_200_200/0/1631353289340?e=1745452800&v=beta&t=bhPRUL-c8G0vZR4aQSEW82z5n5i0hXveUE8IwOgn_lU",
    link: "https://www.example.com/nodejs-workshop",
    author: "Jane Smith",
    date: "15 août 2023",
    isVerifyed: false,
    isFree: false,
    price: 30,
    currency: "$",
    duration: "6h",
  },
];
