export const formations = [
  {
    id: 1,
    title:
      "Créer un menu hamburger moderne avec seulement HTML et CSS (Tutoriel rapide)",
    description:
      "Dans cette vidéo, découvre comment coder un **menu hamburger interactif avec uniquement HTML et CSS**. Pas besoin de JavaScript, parfait pour débutants ou développeurs voulant améliorer leurs bases en CSS !",
    src: "youtube",
    type: "video",
    image:
      "https://i.pinimg.com/originals/38/93/93/389393d4feaa13b84507fffb10a7daa2.gif",
    link: "https://www.youtube.com/watch?v=hDw0QGGdZI4&t=122s",
    author: "Elvin code",
    authorImage: "/assets/users/elvin.jpeg",
    date: "20 janvier 2023",
    isVerifyed: true,
    isFree: true,
    price: 40,
    currency: "$",
    duration: "45 min",
  },
  {
    id: 2,
    title: "Comprendre les fonctions exponentielles",
    description:
      "Apprends à maîtriser les bases des fonctions exponentielles, étape par étape.",
    src: "document",
    type: "pdf",
    image:
      "https://i.pinimg.com/736x/39/1f/12/391f120e3f09e96fa6a9065fde64e67e.jpg",
    link: "https://www.example.com/fonctions-exponentielles",
    author: "Mathématiques pour tous",
    date: "10 février 2023",
    isVerifyed: true,
    isFree: false,
    price: 10,
    currency: "$",
    duration: "2h",
  },
  {
    id: 3,
    title: "Introduction à JavaScript pour les débutants",
    description:
      "Un guide interactif pour apprendre les bases de JavaScript et commencer à coder.",
    src: "youtube",
    type: "video",
    image:
      "https://i.pinimg.com/736x/0e/4f/dc/0e4fdce8ac22e09688c580e5bc4dcd7d.jpg",
    link: "https://www.youtube.com/watch?v=v3Ho7QVaTXM",
    author: "Melvynx",
    date: "15 mars 2023",
    isVerifyed: true,
    isFree: true,
    price: 0,
    currency: "$",
    duration: "1h 30 min",
  },
  {
    id: 4,
    title: "Les bases de React.js",
    description:
      "Découvre les concepts fondamentaux de React pour créer des interfaces dynamiques.",
    src: "course",
    type: "video",
    image:
      "https://i.pinimg.com/736x/b7/95/ac/b795aca8f3911c6e0fedc879d7dc2979.jpg",
    link: "https://www.udemy.com/course/react-for-beginners/",
    author: "John Doe",
    date: "5 mai 2023",
    isVerifyed: true,
    isFree: false,
    price: 42000,
    currency: "Fc",
    duration: "3h",
  },
  {
    id: 5,
    title: "Apprendre Tailwind CSS",
    description:
      "Explore comment styliser vos applications modernes rapidement grâce à Tailwind CSS.",
    src: "blog",
    type: "article",
    image:
      "https://i.pinimg.com/736x/a4/b7/4a/a4b74a0363d04c1f1fe8c951592a3a8a.jpg",
    link: "https://tailwindcss.com/docs/installation",
    author: "Tailwind Team",
    date: "12 avril 2023",
    isVerifyed: true,
    isFree: true,
    price: 0,
    currency: "$",
    duration: "30 min",
  },
  {
    id: 6,
    title: "Guide pratique de MongoDB",
    description:
      "Apprends à utiliser MongoDB pour stocker et interroger des données efficacement.",
    src: "ebook",
    type: "pdf",
    image:
      "https://i.pinimg.com/736x/69/78/3a/69783ad8d0e5f05042e2dbb58860cd83.jpg",
    link: "https://learn.mongodb.com/",
    author: "MongoDB University",
    date: "30 juin 2023",
    isVerifyed: true,
    isFree: true,
    price: 0,
    currency: "$",
    duration: "4h",
  },
  {
    id: 7,
    title: "Créer des animations CSS avancées",
    description:
      "Un cours approfondi pour maîtriser les animations CSS, de simples transitions aux animations complexes.",
    src: "youtube",
    type: "video",
    image:
      "https://i.pinimg.com/originals/a7/b0/15/a7b015d343ad801ad6da8c242dc6ae06.gif",
    link: "https://www.youtube.com/watch?v=avw21xGxflU",
    author: "Bob Frontend",
    date: "7 juillet 2023",
    isVerifyed: true,
    isFree: true,
    price: 0,
    currency: "$",
    duration: "2h 15 min",
  },
  {
    id: 8,
    title: "Atelier de développement Node.js",
    description:
      "Un atelier pratique pour apprendre à créer des API backend avec Node.js.",
    src: "course",
    type: "workshop",
    image:
      "https://i.pinimg.com/736x/4e/52/2c/4e522cf908acb79676cfe6555dead5f9.jpg",
    link: "https://www.example.com/nodejs-workshop",
    author: "Jane Smith",
    date: "15 août 2023",
    isVerifyed: false,
    isFree: false,
    price: 30,
    currency: "$",
    duration: "6h",
  },
];
