const meets = [
  {
    id: 1,
    title: "Live Coding",
    description:
      "Retrouvez-nous au Live Coding chaque jeudi soir avec Vander Otis !   Apprenez, échangez et codez en direct. 💻🔥",
    type: "meet",
    date: "Chaque Jeudi",
    time: "19h30",
    location: "online",
    link: "https://lnkd.in/gzv4QQPa",
    imageUrl: "/assets/events/live-coding.jpeg",
    author: "Vander Otis",
    authorUrl: "https://www.linkedin.com/in/vancodes/",
    authorImageUrl: "/assets/users/Vander-Otis.jpg",
    isVerifyed: true,
    isFree: true,
    price: 0,
    currency: "$",
    duration: "45 min",
    isPinned: true,
    isUpcoming: true,
  },
  {
    id: 2,
    title: "Bootcamp Git & GitHub pour Débutants",
    description:
      "Apprenez à déployer vos sites Web efficacement !  ✅ Théorie & Pratique pour maîtriser les bases.",
    type: "meet",
    date: "25 janvier 2025",
    time: "12h00 (GMT+2)",
    location: "online",
    link: "https://lnkd.in/guKKGGgM",
    imageUrl: "/assets/events/bootcamp-git_github.jpeg",
    author: "Jacques Milenge",
    authorUrl: "https://www.linkedin.com/in/jacques-milenge-162958242/",
    authorImageUrl:
      "https://media.licdn.com/dms/image/v2/D4D03AQGkMTqaoKFn7w/profile-displayphoto-shrink_400_400/profile-displayphoto-shrink_400_400/0/1721066479558?e=1743638400&v=beta&t=0ZZ8QmTGwHLW6Y9GjvtIZMIvp32gd1y0hDg8bMdWzHE",
    isVerifyed: true,
    isFree: true,
    price: 0,
    currency: "$",
    duration: "45 min",
    isPinned: false,
    isUpcoming: false,
  },

  {
    id: 3,
    title: "Club de développeurs",
    description:
      "Explorer, coder et innover ensemble !   ✅ Théorie & Pratique pour maîtriser les bases.",
    type: "bootcamp",
    date: "Chaque Jeudi",
    time: "12h30",
    location: "Salle bac1 info",
    link: "https://lnkd.in/gzv4QQPa",
    imageUrl: "/assets/events/dev-club.jpeg",
    author: "Cercle Scientifique math info",
    authorUrl:
      "https://www.linkedin.com/company/cercle-scientifique-math-info/",
    authorImageUrl: "",
    isVerifyed: true,
    isFree: true,
    price: 0,
    currency: "$",
    duration: "45 min",
    isPinned: true,
    isUpcoming: true,
  },

  {
    id: 4,
    title: "Superintelligence artificielle — Mythe ou réalité imminente ?",
    description:
      "Découvrez ce qu’est vraiment l’IA, la différence entre IA faible et IA forte, et les enjeux de la superintelligence.  Un échange ouvert pour poser vos questions et débattre sur l’avenir de l’IA et son impact sur l’humanité.    Curieux(se) ou passionné(e) ? Rejoignez-nous pour apprendre et échanger dans un cadre interactif !",
    type: "meet",
    date: "18 janvier",
    time: "20h00 (GMT+2)",
    location: "online",
    link: " https://lnkd.in/gqvFvwqu",
    imageUrl: "/assets/events/super_ai.jpeg",
    author: "Djochrist Kuma-Kuma",
    authorUrl: "https://www.linkedin.com/in/djochrist-kuma-kuma-151b3b333/",
    authorImageUrl:
      "https://media.licdn.com/dms/image/v2/D5603AQE9a19JBWXKMA/profile-displayphoto-shrink_400_400/profile-displayphoto-shrink_400_400/0/1729273882054?e=1743638400&v=beta&t=n-5thyDaYcXbh2cwjoYqueGvpIrhxmqB9-qX5Nfe80g",
    isVerifyed: true,
    isFree: true,
    price: 0,
    currency: "$",
    duration: "45 min",
    isPinned: false,
    isUpcoming: false,
  },

  {
    id: 5,
    title: "Créez votre premier site web et relevez un défi stimulant ! 🚀",
    description:
      "- Les bases incontournables de la programmation web.   - Les outils nécessaires pour concevoir un site fonctionnel.",
    type: "bootcamp",
    date: "11 janvier 2025",
    time: "19h30",
    location: "Salle Bac 3 Géo.",
    link: "https://www.linkedin.com/feed/update/urn:li:activity:7282095998678585344/",
    imageUrl: "/assets/events/bootcamp_website.jpeg",
    author: "Elvin Code",
    authorUrl: "https://www.linkedin.com/in/elvincode/",
    authorImageUrl:
      "https://media.licdn.com/dms/image/v2/D4D03AQE3ZDtlH0Vedw/profile-displayphoto-shrink_400_400/profile-displayphoto-shrink_400_400/0/1728655288833?e=1743638400&v=beta&t=HO20egnJqObsPzl67Mjp9q7jQFSegXbSHbz7kN9RE1Q",
    isVerifyed: true,
    isFree: true,
    price: 0,
    currency: "$",
    duration: "45 min",
    isPinned: false,
    isUpcoming: false,
  },

  {
    id: 6,
    title:
      "🎯 Foire aux Questions & Présentation des Outils Informatiques Essentiels 🎯",
    description:
      "Le Cercle Scientifique Math-Info vous propose un moment interactif pour poser toutes vos questions et découvrir des outils essentiels pour avancer sereinement.",
    type: "FAQ",
    date: "19 Décembre 2024",
    time: "12h30",
    location: "Salle Bac 2 Géo.",
    link: "https://lnkd.in/gzv4QQPa",
    imageUrl: "/assets/events/faq.jpeg",
    author: "Cercle Scientifique Math-Info",
    authorUrl:
      "https://www.linkedin.com/company/cercle-scientifique-math-info/posts/?feedView=all",
    authorImageUrl:
      "https://media.licdn.com/dms/image/v2/C4D0BAQEwdzuXWGe55A/company-logo_200_200/company-logo_200_200/0/1656015392633/cercle_scientifique_math_info_logo?e=1746057600&v=beta&t=ljkXEx5cFFsj5sjrfSop0tys_c6PeOqyKFqVGn5EIRs",
    isVerifyed: true,
    isFree: true,
    price: 0,
    currency: "$",
    duration: "45 min",
    isPinned: false,
    isUpcoming: false,
  },
];

export default meets;
